import * as curlconverter from 'curlconverter'

export const languages = {
  ansible: { converter: curlconverter.toAnsibleWarn, hljs: 'yaml', title: 'Ansible' },
  c: { converter: curlconverter.toCWarn, hljs: 'c', title: 'C' },
  csharp: { converter: curlconverter.toCSharpWarn, hljs: 'csharp', title: 'C#' },
  clojure: { converter: curlconverter.toClojureWarn, hljs: 'clojure', title: 'Clojure' },
  // TODO: CFML isn't supported by highlight.js
  cfml: { converter: curlconverter.toCFMLWarn, hljs: 'javascript', title: 'ColdFusion Markup Language', shortTitle: 'CFML' }, // backwards compatibility
  coldfusion: { converter: curlconverter.toCFMLWarn, hljs: 'javascript', title: 'ColdFusion Markup Language', shortTitle: 'CFML' },
  dart: { converter: curlconverter.toDartWarn, hljs: 'dart', title: 'Dart' },
  elixir: { converter: curlconverter.toElixirWarn, hljs: 'elixir', title: 'Elixir' },
  go: { converter: curlconverter.toGoWarn, hljs: 'go', title: 'Go' },
  har: { converter: curlconverter.toHarStringWarn, hljs: 'json', title: 'HAR' },
  http: { converter: curlconverter.toHTTPWarn, hljs: 'http', title: 'HTTP' },
  httpie: { converter: curlconverter.toHttpieWarn, hljs: 'bash', title: 'HTTPie' },
  java: { converter: curlconverter.toJavaWarn, hljs: 'java', title: 'Java + HttpClient' },
  'java-httpurlconnection': { converter: curlconverter.toJavaHttpUrlConnectionWarn, hljs: 'java', title: 'Java + HttpURLConnection' },
  'java-jsoup': { converter: curlconverter.toJavaJsoupWarn, hljs: 'java', title: 'Java + jsoup', shortTitle: 'jsoup' },
  'java-okhttp': { converter: curlconverter.toJavaOkHttpWarn, hljs: 'java', title: 'Java + OkHttp', shortTitle: 'OkHttp' },
  javascript: { converter: curlconverter.toJavaScriptWarn, hljs: 'javascript', title: 'JavaScript + fetch', shortTitle: 'JavaScript' },
  'javascript-jquery': {converter: curlconverter.toJavaScriptJqueryWarn, hljs: 'javascript', title: 'JavaScript + jQuery', shortTitle: 'jQuery'},
  'javascript-xhr': {converter: curlconverter.toJavaScriptXHRWarn, hljs: 'javascript', title: 'JavaScript + XHR', shortTitle: 'XHR'},
  // People googling for "curl json" are probably looking for something else
  json: { converter: curlconverter.toJsonStringWarn, hljs: 'json', title: 'a JSON object', shortTitle: 'JSON' },
  julia: { converter: curlconverter.toJuliaWarn, hljs: 'julia', title: 'Julia' },
  kotlin: { converter: curlconverter.toKotlinWarn, hljs: 'kotlin', title: 'Kotlin' },
  lua: { converter: curlconverter.toLuaWarn, hljs: 'lua', title: 'Lua' },
  matlab: { converter: curlconverter.toMATLABWarn, hljs: 'matlab', title: 'MATLAB' },
  'node-axios': { converter: curlconverter.toNodeAxiosWarn, hljs: 'javascript', title: 'Node + Axios', shortTitle: 'Axios' },
  'node-got': { converter: curlconverter.toNodeGotWarn, hljs: 'javascript', title: 'Node + Got' },
  'node-ky': { converter: curlconverter.toNodeKyWarn, hljs: 'javascript', title: 'Node + Ky' },
  'node-fetch': { converter: curlconverter.toNodeWarn, hljs: 'javascript', title: 'node-fetch' },
  'node-request': { converter: curlconverter.toNodeRequestWarn, hljs: 'javascript', title: 'Node + request' },
  'node-superagent': { converter: curlconverter.toNodeSuperAgentWarn, hljs: 'javascript', title: 'Node + SuperAgent', shortTitle: 'SuperAgent' },
  'node-http': { converter: curlconverter.toNodeHttpWarn, hljs: 'javascript', title: 'Node + http', shortTitle: 'Node' },
  objectivec: { converter: curlconverter.toObjectiveCWarn, hljs: 'objectivec', title: 'Objective-C' },
  ocaml: { converter: curlconverter.toOCamlWarn, hljs: 'ocaml', title: 'OCaml' },
  perl: { converter: curlconverter.toPerlWarn, hljs: 'perl', title: 'Perl' },
  php: { converter: curlconverter.toPhpWarn, hljs: 'php', title: 'PHP' },
  'php-guzzle': { converter: curlconverter.toPhpGuzzleWarn, hljs: 'php', title: 'PHP + Guzzle', shortTitle: 'Guzzle' },
  'powershell-restmethod': { converter: curlconverter.toPowershellRestMethodWarn, hljs: 'powershell', title: 'PowerShell + Invoke-RestMethod', shortTitle: 'PowerShell' },
  'powershell-webrequest': { converter: curlconverter.toPowershellWebRequestWarn, hljs: 'powershell', title: 'PowerShell + Invoke-WebRequest', shortTitle: 'PowerShell' },
  python: { converter: curlconverter.toPythonWarn, hljs: 'python', title: 'Python' },
  'python-httpclient': { converter: curlconverter.toPythonHttpWarn, hljs: 'python', title: 'Python + http.client' },
  r: { converter: curlconverter.toRWarn, hljs: 'r', title: 'R + httr' },
  'r-httr2': { converter: curlconverter.toRHttr2Warn, hljs: 'r', title: 'R + httr2' },
  ruby: { converter: curlconverter.toRubyWarn, hljs: 'ruby', title: 'Ruby + Net::HTTP' },
  'ruby-httparty': { converter: curlconverter.toRubyHttpartyWarn, hljs: 'ruby', title: 'Ruby + HTTParty' },
  rust: { converter: curlconverter.toRustWarn, hljs: 'rust', title: 'Rust' },
  swift: { converter: curlconverter.toSwiftWarn, hljs: 'swift', title: 'Swift' },
  wget: { converter: curlconverter.toWgetWarn, hljs: 'bash', title: 'Wget' },
}
